config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root "admins/fish#index"

  namespace :admins do
    resources :fish do
      member do
        delete :delete_image
      end
    end
    resources :categories do
      resources :fish_categories
    end
    namespace :fish do
      post 'csv_upload'
    end
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def say_hello
    'Hello'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :fish_category
    has_many :fish, through: :fish_category
end

app/models/fish.rb
class Fish < ApplicationRecord
    enum status: { draft: 0, published: 1, archived: 2  }
    validates_numericality_of :stock, :only_integer => true, :greater_than_or_equal_to => 0
    validates_numericality_of :price, :only_integer => true, :greater_than_or_equal_to => 0
    has_many :fish_category, dependent: :destroy
    has_many :category, through: :fish_category
    has_one_attached :primary_image
    has_many_attached :supported_images
end

app/models/fish_category.rb
class FishCategory < ApplicationRecord
  belongs_to :fish
  belongs_to :category
end

app/controllers/admins/categories_controller.rb
class Admins::CategoriesController < ApplicationController
    before_action :authenticate_admin!,only: [:create,:edit,:destroy]
    def index
        @categories = Category.all 
        @categories = @categories.page(params[:page]).per(5)
    end

    def show
        @categories = Category.find(params[:id])
    end

    def new
        puts "This is how you print out something."
        @categories = Category.new
    end
    
    def edit
        @categories = Category.find(params[:id])
    end

    def create
        @categories = Category.create(category_params)
    
        if @categories.invalid?
          flash[:error] = @categories.errors.full_messages
        end
    
        redirect_to action: :index
    end
    
    def update
        @categories = Category.find(params[:id])
        @categories.update(category_params)
        redirect_to action: :index
    end

    def destroy
        @categories = Category.find(params[:id])
        @categories.destroy
        redirect_to action: :index
    end

    private
    def category_params
        params.require(:category).permit(:title, :description)
    end
end

app/controllers/admins/fish_categories_controller.rb
class Admins::FishCategoriesController < ApplicationController
    before_action :authenticate_admin!
    def create
        @categories = Category.find params[:category_id]
        fish = Fish.find_by(description: fish_category_params[:result])
        @categories.fish_category.create(fish: fish)
        # print("This is params ")
        # print("\n")
        # print(fish_category_params)
        redirect_to admins_categories_path
    end
    
    private
    
    def fish_category_params
        params.require(:fish_category).permit(:result)
    end
end

app/controllers/admins/fish_controller.rb
class Admins::FishController < ApplicationController
  before_action :authenticate_admin!,only: [:create,:edit,:destroy,:csv_upload]
  def index
    @fish = Fish.all
    @fish = @fish.page(params[:page]).per(5)
    respond_to do |format|
      format.html
      format.csv { send_data generate_csv(Fish.all), file_name: 'fish.csv' }
    end
  end

  def show
    @fish = Fish.find(params[:id])
  end

  def new
    puts "This is how you print out something."
    @fish = Fish.new
  end

  def edit
    @fish = Fish.find(params[:id])
  end

  def create
    @fish = Fish.create(fish_params)
    if @fish.invalid?
      flash[:error] = @fish.errors.full_messages
    end

    redirect_to action: :index
  end

  def update
    @fish = Fish.find(params[:id])
    @fish.update(fish_params)
    print("This is Fish Params")
    print("\n")
    print(fish_params[:primary_image])
    print("\n")
    print(fish_params[:supported_images])
    redirect_to action: :index
  end

  def destroy
    @fish = Fish.find(params[:id])
    @fish.destroy
    redirect_to action: :index
  end

  def csv_upload
    data = params[:csv_file].read.split("\n")
    data.each do |line|
      attr = line.split(",").map(&:strip)
      Fish.create title: attr[0], description: attr[1], stock: attr[2], price: attr[3]
    end
    redirect_to action: :index
  end

  def delete_image
    @image = ActiveStorage::Attachment.find(params[:id])
    @image.purge
    redirect_to action: :index
  end

  private

  def generate_csv(articles)
    articles.map { |a| [a.title, a.description,a.stock,a.price, a.created_at.to_date].join(',') }.join("\n")
  end

  def fish_params
    params.require(:fish).permit(:title, :description,:stock,:price,:primary_image,:supported_images => [],:status => []).tap do |w|
      w[:status] = w[:status][1].to_i
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @search = params[:search]

    @articles = Article.all
    @articles = @articles.search(@search) if @search.present?
    @articles = @articles.page(params[:page])
                  .order(updated_at: :desc).per(10)

    respond_to do |format|
      format.html
      format.csv { send_data generate_csv(Article.all), file_name: 'articles.csv' }
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    puts "This is how you print out something."
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.create(article_params)

    if @article.invalid?
      flash[:error] = @article.errors.full_messages
    end

    redirect_to action: :index
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to action: :index
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to action: :index
  end

  def csv_upload
    data = params[:csv_file].read.split("\n")
    data.each do |line|
      attr = line.split(",").map(&:strip)
      Article.create title: attr[0], body: attr[1]
    end
    redirect_to action: :index
  end

  private

  def generate_csv(articles)
    articles.map { |a| [a.title, a.body, a.created_at.to_date].join(',') }.join("\n")
  end

  def article_params
    params.require(:article).permit(:title, :body, category_ids: [])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find params[:article_id]
    @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :text)
  end
end

app/controllers/test_articles_controller.rb
class TestArticlesController < ApplicationController
  #caches_page :index

  def index
    @articles = Article.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fish_helper.rb
module FishHelper
end

app/views/admins/categories/_form.slim
= form_for [:admins,category] do |f|
  div = f.text_field :title, placeholder: 'Title'
  div = f.text_area :description, placeholder: 'Write the description here'
  div = f.submit 'Submit Category'

app/views/admins/categories/edit.slim
h1 Edit Product

div = link_to 'Back', admins_categories_path
br
= render 'form', category: @categories

app/views/admins/categories/index.slim
h1 This is category list
row 
  -if current_admin
        span.ml-3 = current_admin.email
        span.ml-3 = link_to 'Logout', destroy_admin_session_path , method: :delete
  -else
    span.ml = link_to 'Login', admin_session_path
row.mt-2
    table.table.table-bordered.table-striped.table-hover
      thead.thead-dark
        tr
          th ID
          th Title
          th Description
          th Action
      tbody
        - @categories.each do |a|
          tr
            td = a.id
            td.font-weight-bold = a.title
            td = a.description
            td
              span.ml-2 
                = link_to admins_category_path(a) do
                  i.fas.fa-eye
              -if current_admin
                span.ml-2
                  = link_to edit_admins_category_path(a) do
                    i.fas.fa-pen
                span.ml-2
                  = link_to admins_category_path(a), method: :delete, data: { confirm: "Are you sure?" } do
                    i.fas.fa-trash

span.ml = link_to 'Back',admins_fish_index_path
.row
  .col-6
    = paginate @categories
  -if current_admin
    .col-6
      .float-right
        = link_to new_admins_category_path do
          = button_tag 'Add new category', class: 'btn btn-primary'

app/views/admins/categories/new.slim
h1 Add new category

div = link_to 'Back', admins_categories_path
br
= render 'form', category: @categories

app/views/admins/categories/show.slim
h1 = @categories.title
div = link_to 'Back', admins_categories_path
hr
h2 = "Description"
hr
div = @categories.description
hr
h2 = "List of the fish in this category"
div
  - @categories.fish.each do |f|
    div = link_to "#{f.title}" , admins_fish_path(f)

-if current_admin
  h2 Add new fish to this category
  = form_with model: [:admins,@categories, @categories.fish_category.build] do |f|
    div = f.collection_select :result, Fish.all ,:description,:title
    div = f.submit 'Add Category'

app/views/admins/fish/_form.slim
= form_with model: [:admins, fish] do |f|
  div = f.text_field :title, placeholder: 'Title'
  div = f.text_area :description, placeholder: 'Write the description here'
  div = f.number_field :stock, placeholder: 'Stock'
  div = f.number_field :price, placeholder: 'Price'
  h3 Status
  div = f.collection_check_boxes :status, Fish.statuses.map, :last, :first
  h3 Primary Image 
  div = f.file_field :primary_image
  h3 Other Images 
  div = f.file_field :supported_images, multiple: true
  div = f.submit 'Submit Product'

app/views/admins/fish/edit.slim
h1 Edit Product
-if @fish.primary_image.attached?
  div = image_tag(@fish.primary_image)
  div = link_to 'Remove', delete_image_admins_fish_url(@fish.primary_image.id),method: :delete
-if @fish.supported_images.attached?
  h2 Others
  -(0...@fish.supported_images.count).each do |f|
    div = image_tag(@fish.supported_images[f])
    div = link_to 'Remove', delete_image_admins_fish_url(@fish.supported_images[f].id),method: :delete

br
= render 'form', fish: @fish
div = link_to 'Back', admins_fish_index_path

app/views/admins/fish/index.slim
h1 This is products list
row
  -if current_admin
        span.ml-3 = current_admin.email
        span.ml-3 = link_to 'Logout', destroy_admin_session_path , method: :delete
  -else
    span.ml = link_to 'Login', admin_session_path
row.mt-2
    table.table.table-bordered.table-striped.table-hover
      thead.thead-dark
        tr
          th ID
          th Title
          th Description
          th Stock 
          th Price
          th Status
          th Created at
          th Updated at
          th Image
          th Action
      tbody
        - @fish.each do |a|
          tr
            td = a.id
            td.font-weight-bold = a.title
            td = a.description
            td = a.stock
            td = "#{a.price} Baht" 
            td = a.status.presence || 'NA'
            td.font-weight-light = "#{time_ago_in_words(a.created_at)} Ago"
            td.font-weight-light = "#{time_ago_in_words(a.updated_at)} Ago"
            -if a.primary_image.attached?
              td = image_tag(a.primary_image)
            -else
              td = 'None'
            td
              span
                = link_to admins_fish_path(a) do
                  i.fas.fa-eye
              -if current_admin
                span.ml-2
                  = link_to edit_admins_fish_path(a) do
                    i.fas.fa-pen
                span.ml-2
                  = link_to admins_fish_path(a), method: :delete, data: { confirm: "Are you sure?" } do
                    i.fas.fa-trash

span.ml = link_to 'Category',admins_categories_path
-if current_admin
  div.mb-2
    = link_to new_admins_fish_path do
      = button_tag 'Add new Product', class: 'btn btn-primary'

.row
  .col-6
    = paginate @fish

.row
  .col
    .float-right
      div.mb-2
      = link_to '/fish.csv' do
        = button_tag 'Download', class: 'btn btn-primary'
    -if current_admin
      = form_tag admins_fish_csv_upload_path, multipart: true do
        div = file_field_tag :csv_file
        div = submit_tag :upload

app/views/admins/fish/new.slim
h1 Add new product

div = link_to 'Back', admins_fish_index_path
br
= render 'form', fish: @fish

app/views/admins/fish/show.slim
h1 = @fish.title
-if @fish.primary_image.attached?
  div = image_tag(@fish.primary_image)
  div = link_to 'Remove', delete_image_admins_fish_url(@fish.primary_image.id),method: :delete
-if @fish.supported_images.attached?
  h2 Others
  -(0...@fish.supported_images.count).each do |f|
    div = image_tag(@fish.supported_images[f])
    div = link_to 'Remove', delete_image_admins_fish_url(@fish.supported_images[f].id),method: :delete
hr
h2 = "Categories"
div
  - @fish.category.each do |f|
    div = link_to "#{f.title}" , admins_categories_path(f)
hr
h3 = "Description"
div = @fish.description
hr
h3 = "Stock"
div  = @fish.stock
hr
h3 = "Price"
hr
div = @fish.price
div = link_to 'Back', admins_fish_index_path

app/views/articles/_form.slim
= form_with model: article do |f|
  div Title
  div = f.text_field :title, placeholder: 'Title'
  div Body
  div = f.text_area :body, placeholder: 'Write content here'
  div Category
  div = f.collection_check_boxes :category_ids, Category.all, :id, :name
  div = f.submit 'Submit Article'

app/views/articles/edit.slim
h1 Edit article

div = link_to 'Back', articles_path
br
= render 'form', article: @article

app/views/articles/index.slim
.row
  .col-6
    h1 This is articles list
  .col-6
    .float-right
      span = current_admin.email
      span.ml-3 = "#{current_admin.firstname} #{current_admin.lastname}"
      span.ml-3 = link_to 'Logout', destroy_admin_session_path

.row
  .col-10
    = form_tag articles_path, method: :get do
      = text_field_tag 'search', @search, placeholder: 'Type something',
        class: 'form-control'
  .col-2
    = link_to articles_path(format: :csv) do
      = button_tag 'Download CSV', class: 'btn btn-secondary float-right'
.row.mt-2
  .col
    table.table.table-bordered.table-striped.table-hover
      thead.thead-dark
        tr
          th ID
          th Status
          th Product
          th Description
          th Categories
          th No. Comments
          th Created at
          th Updated at
          th Action
      tbody
        - @articles.each do |a|
          tr
            td = a.id
            td = a.status
            td.font-weight-bold = a.title.first(16)
            td = a.body
            td = a.categories&.map(&:name)&.join(',').presence || 'NA'
            td = a.comments.count
            td.font-weight-light = "#{time_ago_in_words(a.created_at)} Ago"
            td.font-weight-light = "#{time_ago_in_words(a.updated_at)} Ago"
            td
              span
                = link_to article_path(a) do
                  i.fas.fa-eye
              span.ml-3
                = link_to edit_article_path(a) do
                  i.fas.fa-pen
              span.ml-3
                = link_to article_path(a), method: :delete, data: { confirm: "Are you sure?" } do
                  i.fas.fa-trash

.row
  .col-6
    = paginate @articles
  .col-6
    .float-right
      = link_to new_article_path do
        = button_tag 'Add new Article', class: 'btn btn-primary'

div
  hr

.row
  .col
    = form_tag articles_csv_upload_path, multipart: true do
      div = file_field_tag :csv_file
      div = submit_tag :upload

app/views/articles/new.slim
h1 Add new article

div = link_to 'Back', articles_path
br
= render 'form', article: @article

app/views/articles/show.slim
h1 = @article.title
div = link_to 'Back', articles_path
hr
div = @article.body
hr
h2 Comments Section
div
  - @article.comments.each do |comment|
    div = "#{comment.author} Wrote : #{comment.text}"
hr
h2 Add new Comment Section
= form_with model: [@article, @article.comments.build] do |f|
  div = f.text_field :author, placeholder: 'Author'
  div = f.text_area :text, placeholder: 'Write text here'
  div = f.submit 'Submit Comment'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css'%>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container">
      <h1 style="color: red;">
        <%= flash[:error]&.join(',') %>
      </h1>
      <%= yield %>

      <%= javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.slim.min.js' %>
      <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js' %>
      <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js' %>
    </div>
  </body>
</html>

app/views/test_articles/index.slim
.row
  .col-12
    h1 This is test articles list

.row.mt-2
  .col
    table.table.table-bordered.table-striped.table-hover
      thead.thead-dark
        tr
          th ID
          th Title
          th Body
          th No. Comments
          th Created at
          th Updated at
          th Action
      tbody
        - @articles.each do |a|
          - cache a do
            tr
              td = a.id
              td.font-weight-bold = a.title
              td = a.body
              td = a.comments.count
              td.font-weight-light = "#{time_ago_in_words(a.created_at)} Ago"
              td.font-weight-light = "#{time_ago_in_words(a.updated_at)} Ago"
              td
                span
                  = link_to article_path(a) do
                    i.fas.fa-eye
                span.ml-3
                  = link_to edit_article_path(a) do
                    i.fas.fa-pen
                span.ml-3
                  = link_to article_path(a), method: :delete, data: { confirm: "Are you sure?" } do
                    i.fas.fa-trash